# PoWFaucet config (example)
version: 2

### General Settings

# faucet database (defaults to local sqlite)
database:
  driver: "sqlite"
  file: "faucet-store.db"

# logfile for faucet events (comment out for no logging)
faucetLogFile: "faucet-events.log"

# path to file to write the process pid to (comment out to disable)
faucetPidFile: "faucet-pid.txt"

# faucet http/ws server port
serverPort: 8080

# number of http proxies in front of this faucet
httpProxyCount: 0

# title of the faucet
faucetTitle: "Mordor Testnet PoW Faucet"

# url to image displayed on the startpage
faucetImage: "/images/fauceth_420.jpg"

# Additional HTML content for the start page
faucetHomeHtml: |
  <div class='pow-info'>
    <h5>Welcome to the ETCMC Mordor PoW Faucet!</h5>
    This faucet provides free testnet METC on the Mordor Testnet.<br>
    To ensure fair distribution and prevent abuse, users must perform a small mining task before claiming funds.
  </div>
  <div class='pow-info'>
    <h5>How Does It Work?</h5>
    Simply enter your ETC address and start mining.  
    Once you've earned enough testnet METC, stop mining and claim your rewards.
  </div>
  <div class='pow-info'>
    <h5>How to help the faucet?</h5>
    Replenish the faucet by sending funds you don't need anymore to:<br>
    {faucetWallet}
  </div>


# random secret string that is used by the faucet to "sign" session data, so sessions can be restored automatically by clients when faucet is restarted / crashed
# use a random string and do not share / reuse it anywhere. Everyone knowing this secret is theoretically able to claim rewards from the faucet without mining.
faucetSecret: "RandomStringThatShouldBeVerySecret!"

# Mordor testnet RPC host
ethRpcHost: "https://rpc.mordor.etccooperative.org"

# faucet wallet private key (hex, without 0x prefix)
ethWalletKey: "0x----"  # Replace with your wallet's private key

# EVM chain id (Mordor Testnet is 63)
ethChainId: 63

# symbol (short name) of the coin that can be mined
faucetCoinSymbol: "METC"  # METC for Mordor testnet

# type of coin that can be mined
faucetCoinType: "native"

# transaction gas limit
# use 21000 to prevent transactions to contracts
ethTxGasLimit: 21000

# use legacy (non-eip1559) transaction type
# true: Type 0 (Legacy Transactions), false: Type 2 (EIP1559 Transactions)
ethLegacyTx: true

# max transaction gas fee (in wei)
# used as limit for legacy transactions (faucet won't build transactions with higher gas price)
ethTxMaxFee: 100000000000  # 100 gwei

# max transaction priority fee (in wei)
ethTxPrioFee: 2000000000  # 2 gwei

# max number of unconfirmed transactions to create simultaneously
ethMaxPending: 12

# queue transactions and wait for funding when faucet is out of funds (show "No Funds" error when false)
ethQueueNoFunds: true

# link to eth transaction explorer with {txid} as placeholder for transaction id or null for no link
ethTxExplorerLink: "https://etc-mordor.blockscout.com/tx/{txid}"
### Withdrawal Restrictions
maxDropAmount: 1000000000000000000  # 1 METC
minDropAmount: 10000000000000000    # 0.01 METC
sessionTimeout: 43200  # 12 hours
sessionCleanup: 2592000  # 30 days
sessionSaveTime: 120

### Protection Mechanisms
modules:
  ## CAPTCHA Protection
  captcha:
    enabled: true
    provider: "hcaptcha"
    siteKey: "YOUR_HCAPTCHA_SITE_KEY"
    secret: "YOUR_HCAPTCHA_SECRET_KEY"
    checkSessionStart: false
    checkBalanceClaim: false

  ## IP-Info module
  ipinfo:
    enabled: true
    apiUrl: "http://ip-api.com/json/{ip}?fields=21155839"
    cacheTime: 86400  # 1 day
    required: false

  ## ETH Info Restrictions
  ethinfo:
    enabled: true
    maxBalance: 50000000000000000000  # 50 METC
    denyContract: true

  ## Faucet Balance Check - Only dispense if at least 100 METC available
  faucet-balance:
    enabled: true
    minBalanceRequired: 100000000000000000000  # 100 METC
    fixedRestriction:
      1000000000000000000000: 90 # 90% if lower than 1000 METC
      100000000000000000000: 10  # 10% if lower than 100 METC
    dynamicRestriction:
      targetBalance: 1100000000000000000000 # No restriction if >1100 METC

  ## Outflow Limits - Max 10 METC per user per 24 hours
  faucet-outflow:
    enabled: true
    amount: 10000000000000000000  # 10 METC
    duration: 86400  # 1 day (24 hours)
    lowerLimit: -500000000000000000000  # -500 METC
    upperLimit: 500000000000000000000   # 500 METC

  ## Proof of Work (mining) protection
  pow:
    enabled: true
    powShareReward: 2000000000000000  # 0.002 METC
    penalty: 10